Repository pagopa/gitops, pull requests merged in 2021-09, with the labels that each got.

#109 Add pipelines for `@pagopa/express-azure-functions`
  azure-devops/projects/pagopa-packages-projects/express-azure-functions.tf
  azure-devops/projects/pagopa-packages-projects/io-spid-commons.tf
  azure-devops/projects/pagopa-packages-projects/openapi-codegen-ts.tf
  azure-devops/projects/pagopa-packages-projects/provider.tf
  azure-devops/projects/pagopa-packages-projects/secrets.tf
  azure-devops/projects/pagopa-packages-projects/service_connections.tf
  azure-devops/projects/pagopa-packages-projects/ts-commons.tf
Labels: status: applied

#110 [IOPAY-262] api-test pipeline for pagopa-payments-tests
  azure-devops/projects/pagopa-projects/pagopa-payments-tests.tf
Labels: status: applied

#114 Cstar iac pipeline
  azure-devops/projects/cstar-iac/iac-deploy.tf
  azure-devops/projects/cstar-iac/project.tf
  azure-devops/projects/cstar-iac/provider.tf
  azure-devops/projects/cstar-iac/secrets.tf
  azure-devops/projects/cstar-iac/service_connections.tf
Labels: status: applied

#116 [CEN-668] Code Review and Deploy Pipelines for FA Customer Microservice
  azure-devops/projects/cstar-projects/fa-ms-customer.tf
Labels: status: applied

#112 [PM-164] mock psp pipeline
  azure-devops/projects/pagopa-projects/pagopa-mock-psp.tf
Labels: status: applied, no merge

#113 [PCFG-14] added pipeline configuration for `@pagopa/pagopa-api-config` repo
  azure-devops/projects/pagopa-projects/pagopa-api-config.tf
  azure-devops/projects/pagopa-projects/service_connections.tf
Labels: status: applied, no merge

#127 [CEN-681] Pipeline for FA File Storage microservice
  azure-devops/projects/cstar-projects/fa-ms-file-storage.tf
Labels: status: applied

#125 [CEN-679] Pipeline for FA Invoice Manager microservice
  azure-devops/projects/cstar-projects/fa-ms-invoice-manager.tf
Labels: status: applied

#124 [CEN-678] Pipelines for FA Merchant microservice
  azure-devops/projects/cstar-projects/fa-ms-merchant.tf
Labels: status: apply in progress

#128 Add api.dev.platform.pagopa.it TLS cert
  azure-devops/projects/pagopa-projects/locals.tf
  azure-devops/projects/pagopa-projects/service_connections.tf
  azure-devops/projects/pagopa-projects/tlscert-dev-api-dev-platform-pagopa-it.tf
Labels: status: applied

#129 [PCFG-14] added pipeline certification for dev
  azure-devops/projects/pagopa-projects/tlscert-dev-management-dev-platform-pagopa-it.tf
  azure-devops/projects/pagopa-projects/tlscert-dev-portal-dev-platform-pagopa-it.tf
Labels: status: applied

#132 [#IP-401] set `AGENT_POOL` variable for IO projects
  azure-devops/projects/eucovidcert-projects/io-functions-eucovidcerts.tf
  azure-devops/projects/eucovidcert-projects/locals.tf
  azure-devops/projects/io-backend-projects/io-backend.tf
  azure-devops/projects/io-backend-projects/io-functions-admin.tf
  azure-devops/projects/io-backend-projects/io-functions-app.tf
  azure-devops/projects/io-backend-projects/io-functions-assets.tf
  azure-devops/projects/io-backend-projects/io-functions-public.tf
  azure-devops/projects/io-backend-projects/io-functions-services.tf
  azure-devops/projects/io-backend-projects/io-pagopa-proxy.tf
  azure-devops/projects/io-backend-projects/locals.tf
  azure-devops/projects/io-developer-portal-projects/io-developer-portal-backend.tf
Labels: status: applied

#131 [PCFG-14] added pipeline certificates - PROD
  azure-devops/projects/eucovidcert-projects/io-functions-eucovidcerts.tf
  azure-devops/projects/eucovidcert-projects/locals.tf
  azure-devops/projects/io-backend-projects/locals.tf
  azure-devops/projects/pagopa-projects/service_connections.tf
  azure-devops/projects/pagopa-projects/tlscert-dev-api-dev-platform-pagopa-it.tf
  azure-devops/projects/pagopa-projects/tlscert-dev-management-dev-platform-pagopa-it.tf
  azure-devops/projects/pagopa-projects/tlscert-dev-portal-dev-platform-pagopa-it.tf
  azure-devops/projects/pagopa-projects/tlscert-prod-api-platform-pagopa-it.tf
  azure-devops/projects/pagopa-projects/tlscert-prod-management-platform-pagopa-it.tf
  azure-devops/projects/pagopa-projects/tlscert-prod-portal-platform-pagopa-it.tf
  azure-devops/projects/pagopa-projects/tlscert-uat-api-uat-platform-pagopa-it.tf
  azure-devops/projects/pagopa-projects/tlscert-uat-management-uat-platform-pagopa-it.tf
  azure-devops/projects/pagopa-projects/tlscert-uat-portal-uat-platform-pagopa-it.tf
Labels: status: applied

#134 Add pagoPA iac pipelines
  azure-devops/projects/pagopa-iac-projects/iac.tf
  azure-devops/projects/pagopa-iac-projects/locals.tf
  azure-devops/projects/pagopa-iac-projects/project.tf
  azure-devops/projects/pagopa-iac-projects/provider.tf
  azure-devops/projects/pagopa-iac-projects/secrets.tf
  azure-devops/projects/pagopa-iac-projects/service_connections.tf
  azure-devops/projects/pagopa-projects/service_connections.tf
Labels: status: applied

#135 CSTAR split deploy-code review for iac
  azure-devops/projects/cstar-iac-projects/iac.tf
  azure-devops/projects/cstar-iac-projects/locals.tf
  azure-devops/projects/cstar-iac-projects/secrets.tf
  azure-devops/projects/pagopa-iac-projects/secrets.tf
Labels: status: applied
